package com.qweather.leframework.base.rbac.user_log.service;

import com.qweather.leframework.base.rbac.user_log.service.po.UserLogEntity;

/**
 * Created at 2022-11-07T15:56:56+08:00
 * Generated by Le Generator, created by xiaole
 *
 * @author dongjunchen
 */
public interface UserLogService {

    UserLogQuery createUserLogQuery();

    UserLogEntity createUserLog();

    void saveUserLog(UserLogEntity entity);

    void addUserLog(Long userId, String userEmail, UserLogType userLogType, Object object);

    void deleteUserLog(Long id);

    void deleteUserLogForever(Long id);

    void deleteUserLogByUserId(Long userId);

}
