package com.qweather.leframework.base.rbac.user_log.service;

import com.qweather.leframework.base.rbac.user_log.service.po.UserLogEntity;
import com.qweather.leframework.model.IdQuery;
import com.qweather.leframework.model.Query;

/**
 * Created at 2022-11-07T15:56:56+08:00
 * Generated by Le Generator, created by xiaole
 *
 * @author dongjunchen
 */
public interface UserLogQuery extends IdQuery<UserLogQuery, UserLogEntity> {

    UserLogQuery userId(Long userId);

    UserLogQuery email(String email);

    UserLogQuery type(UserLogType userLogType);

    UserLogQuery content(String content);

    UserLogQuery orderByUserId(Query.Direction direction);

    UserLogQuery orderByType(Query.Direction direction);

    UserLogQuery orderByContent(Query.Direction direction);
}
