package com.qweather.leframework.base.rbac.user_log.service.po;

import com.qweather.leframework.model.po.LePo;
/**
 * Created at 2022-11-07T15:56:56+08:00
 * Generated by Le Generator, created by xiaole
 *
 * @author dongjunchen
 */
public class UserLogEntity extends LePo {

    /**
     * 用户id
     */
	private Long userId;
    /**
     * 用户邮箱
     */
	private String email;
	/**
     * 日志类型
     */
	private String type;
    /**
     * 日志内容
     */
	private String content;

    public UserLogEntity() {
        super();
    }

    public UserLogEntity(Long id) {
        super(id);
    }

    public Long getUserId() {
        return this.userId;
    }

    public void setUserId(Long userId){
        this.userId = userId;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type){
        this.type = type;
    }

    public String getContent() {
        return this.content;
    }

    public void setContent(String content){
        this.content = content;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }
}