package com.qweather.leframework.base.rbac.user_log.service.cmd;

import com.qweather.leframework.base.rbac.user_log.service.impl.UserLogQueryImpl;
import com.qweather.leframework.model.command.Command;
import org.apache.ibatis.session.SqlSession;

/**
 * Created at 2022-11-07T15:56:56+08:00
 * Generated by Le Generator, created by xiaole
 *
 * @author dongjunchen
 */
public class CountUserLogCmd implements Command<Long> {

    protected UserLogQueryImpl userLogQueryImpl;

    public CountUserLogCmd(UserLogQueryImpl userLogQueryImpl) {
        this.userLogQueryImpl = userLogQueryImpl;
    }

    @Override
    public Long execute(SqlSession sqlSession) {
        return sqlSession.selectOne("com.qweather.leframework.base.rbac.user_log.count", userLogQueryImpl);
    }
}
