package com.qweather.leframework.base.rbac.user_log.service.cmd;

import com.qweather.leframework.model.command.Command;
import org.apache.ibatis.session.SqlSession;

/**
 * Created at 2022-11-07T15:56:56+08:00
 * Generated by Le Generator, created by xiaole
 *
 * @author dongjunchen
 */
public class DeleteUserLogForeverCmd implements Command<Void> {

    protected Long id;

    public DeleteUserLogForeverCmd(Long id) {
        this.id = id;
    }

    @Override
    public Void execute(SqlSession sqlSession) {
        sqlSession.delete("com.qweather.leframework.base.rbac.user_log.deleteForever", id);
        return null;
    }

}
