package com.qweather.leframework.base.rbac.user_log.service.cmd;

import com.qweather.leframework.model.command.Command;
import org.apache.ibatis.session.SqlSession;

/**
 * Created at 2022-11-07T15:56:56+08:00
 * Generated by Le Generator, created by xiaole
 *
 * @author dongjunchen
 */
public class DeleteUserLogByUserIdCmd implements Command<Void> {

    protected Long userId;

    public DeleteUserLogByUserIdCmd(Long userId) {
        this.userId = userId;
    }

    @Override
    public Void execute(SqlSession sqlSession) {
        sqlSession.delete("com.qweather.leframework.base.rbac.user_log.deleteByUserId", userId);
        return null;
    }

}
