package com.qweather.leframework.base.rbac.user_log.service.cmd;

import com.qweather.leframework.base.rbac.user_log.service.po.UserLogEntity;
import com.qweather.leframework.model.command.Command;
import org.apache.ibatis.session.SqlSession;

/**
 * Created at 2022-11-07T15:56:56+08:00
 * Generated by Le Generator, created by xiaole
 *
 * @author xiaole
 */
public class InsertUserLogCmd implements Command<Void> {

    protected UserLogEntity entity;

    public InsertUserLogCmd(UserLogEntity entity) {
        this.entity = entity;
    }

    @Override
    public Void execute(SqlSession sqlSession) {
        if ( entity.getId() == null ) {
            throw new IllegalArgumentException("id can not be null");
        }
        sqlSession.insert("com.qweather.leframework.base.rbac.user_log.insert", entity);
        return null;
    }

}
