package com.qweather.leframework.base.rbac.user_log.service.cmd;

import com.qweather.leframework.base.rbac.user_log.service.impl.UserLogQueryImpl;
import com.qweather.leframework.base.rbac.user_log.service.po.UserLogEntity;
import com.qweather.leframework.model.command.Command;
import org.apache.ibatis.session.SqlSession;

import java.util.List;

/**
 * Created at 2022-11-07T15:56:56+08:00
 * Generated by Le Generator, created by xiaole
 *
 * @author dongjunchen
 */
public class ListUserLogCmd implements Command<List<UserLogEntity>> {

    protected UserLogQueryImpl userLogQueryImpl;

    public ListUserLogCmd(UserLogQueryImpl userLogQueryImpl) {
        this.userLogQueryImpl = userLogQueryImpl;
    }

    @Override
    public List<UserLogEntity> execute(SqlSession sqlSession) {
        return sqlSession.selectList("com.qweather.leframework.base.rbac.user_log.list", userLogQueryImpl);
    }

}
