package com.qweather.leframework.base.rbac.user_log.service.cmd;

import com.qweather.leframework.base.rbac.user_log.service.po.UserLogEntity;
import com.qweather.leframework.model.command.Command;
import org.apache.ibatis.session.SqlSession;

import java.util.List;

/**
 * Created at 2022-11-07T15:56:56+08:00
 * Generated by Le Generator, created by xiaole
 *
 * @author dongjunchen
 */
public class MultiInsertUserLogCmd implements Command<Void> {

    protected List<UserLogEntity> entityList;

    public MultiInsertUserLogCmd(List<UserLogEntity> entityList) {
        this.entityList = entityList;
    }

    @Override
    public Void execute(SqlSession sqlSession) {
        if ( entityList.size() > 0 ) {
            sqlSession.insert("com.qweather.leframework.base.rbac.user_log.multiInsert", entityList);
        }
        return null;
    }

}